name: circus
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip=21.2.*
  - cudatoolkit=11.1.*
  - pytorch=1.10.*
  - torchvision=0.11.*
  - torchaudio=0.10.*
  - pip:
    - gym==0.21.*
    - matplotlib==3.4.*
    - numpy==1.22.*
    - scipy==1.6.*
    - pandas==1.3.*
    - flask==2.0.*
    - pexpect==4.8.*
    - pyyaml==5.1.*
    - pytest==6.2.*
