name: circus
channels: []
dependencies:
  - python=3.9
  - pip=21.2.*
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu111
    - torch==1.10.*
    - numpy
    - scipy
    - pandas
    - matplotlib
    - gym
    - flask
    - pexpect
    - pyyaml
    - pytest
